# Generated by Django 3.1.2 on 2020-10-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0039_auto_20200429_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='card_CVV',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='card_number',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='card_owner',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='card_type',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
