# Generated by Django 3.1.2 on 2020-10-06 22:05

from django.db import migrations, models
import xamine.validators


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0041_auto_20201006_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='card_expiration_date',
            field=models.DateField(validators=[xamine.validators.check_past_date]),
        ),
    ]
