# Generated by Django 3.1.2 on 2020-10-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0042_auto_20201006_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='card_expiration_date',
            field=models.DateField(),
        ),
    ]
