# Generated by Django 3.1.2 on 2020-10-14 02:06

from django.db import migrations, models
import django.db.models.deletion
import partial_date.fields
import xamine.validators


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0043_auto_20201006_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=partial_date.fields.PartialDateField(validators=[xamine.validators.check_past_date]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='card_expiration_date',
            field=partial_date.fields.PartialDateField(validators=[xamine.validators.check_future_date]),
        ),
        migrations.CreateModel(
            name='MedicationOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='med_order', to='xamine.order')),
            ],
        ),
    ]
