# Generated by Django 3.1.2 on 2020-10-15 00:35

from django.db import migrations, models
import xamine.validators


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0044_auto_20201013_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationorder',
            name='billed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(validators=[xamine.validators.check_past_date]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='card_expiration_date',
            field=models.DateField(validators=[xamine.validators.check_future_date]),
        ),
    ]
