# Generated by Django 3.1.2 on 2020-10-16 00:28

from django.db import migrations, models


def add_data_list(apps, schema_editor):
    materials = [
        'X-Ray Film',
        'X-Ray Dye',
        'X-Ray Compensating Filter',
        'Lead Blockers',
        'Film Viewing Accessories',
        'CT Slickers',
        'Ultrasound Gels',
        'Ultrasound Warmers',
        'MRI Slickers',
        'Disposable Skin Markers',
    ]
    add_data(apps, schema_editor, app='xamine', model='Material', items=materials)


def add_data(apps, schema_editor, app, model, items):
    model = apps.get_model(app, model)
    db_alias = schema_editor.connection.alias

    item_objs = []
    for item in items:
        if not model.objects.using(db_alias).filter(name=item).exists():
            item_objs.append(model(name=item))

    model.objects.using(db_alias).bulk_create(item_objs)


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0046_auto_20201016_0019'),
    ]

    operations = [
        migrations.RunPython(add_data_list),
    ]
