# Generated by Django 3.1.2 on 2020-10-21 22:31

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0047_auto_20201016_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainTheme', colorful.fields.RGBColorField()),
                ('mainPrimary', colorful.fields.RGBColorField()),
                ('mainSecondary', colorful.fields.RGBColorField()),
            ],
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xamine.material'),
        ),
    ]
