# Generated by Django 3.1.2 on 2020-10-22 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0048_auto_20201021_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialorder',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xamine.material'),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalBalance', models.IntegerField()),
                ('amountPaid', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_id', to='xamine.patient')),
            ],
        ),
    ]
