# Generated by Django 3.1.2 on 2020-10-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0048_auto_20201021_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='modality_billed',
            field=models.IntegerField(default=0),
        ),
    ]
