# Generated by Django 3.1.2 on 2020-10-27 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0049_order_modality_billed'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='name',
            field=models.CharField(default='default', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balance',
            name='amountPaid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='balance',
            name='totalBalance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='billed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mat_order', to='xamine.order'),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='billed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='med_order', to='xamine.order'),
        ),
    ]
