# Generated by Django 3.1.2 on 2020-11-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0054_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='billed',
            field=models.IntegerField(default=0),
        ),
    ]
